#if !AIRBORNE_EXECUTIONS_THING
global const BETTER_AI_PILOTS_HAS_KARMA_AIRBORNE_EXECUTIONS= 0
#endif
#if AIRBORNE_EXECUTIONS_THING
global const BETTER_AI_PILOTS_HAS_KARMA_AIRBORNE_EXECUTIONS = 1
#endif
